Attempt to fix solution

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-#Management of processes
+# Management of processes
+
 # Function to start manage_my_process
 start_process() {
     if [ -f /var/run/my_process.pid ]; then
@@ -17,9 +18,8 @@ start_process() {
 stop_process() {
     if [ -f /var/run/my_process.pid ]; then
         PID=$(cat /var/run/my_process.pid)
-        kill "$PID"
+        kill "$PID" && echo "manage_my_process stopped" || echo "Error: Failed to stop manage_my_process"
         rm /var/run/my_process.pid
-        echo "manage_my_process stopped"
     else
         echo "manage_my_process is not running."
     fi
@@ -48,3 +48,4 @@ case "$1" in
         exit 1
         ;;
 esac
+
